apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "logstash-operator.serviceAccountName" . }}
rules:
  - apiGroups: [ kopf.dev ]
    resources: [ clusterkopfpeerings ]
    verbs: [ list, watch, patch, get ]

  - apiGroups: [ apiextensions.k8s.io ]
    resources: [ customresourcedefinitions ]
    verbs: [ list, watch ]
  - apiGroups: [ "" ]
    resources: [ namespaces ]
    verbs: [ list, watch ]

  - apiGroups: [ admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1 ]
    resources: [ validatingwebhookconfigurations, mutatingwebhookconfigurations ]
    verbs: [ create, patch ]

  - apiGroups: [ logstash-operator.qalo.de ]
    resources: [ "*" ]
    verbs: [ list, watch, patch ]

  - apiGroups: [ batch, extensions ]
    resources: [ jobs ]
    verbs: [ create ]

  - apiGroups: [ "" ]
    resources: [ configmaps,services ]
    verbs: [ get,create,patch ]

  - apiGroups: [ apps ]
    resources: [ statefulsets ]
    verbs: [ create,patch ]

  - apiGroups: [""]
    resources: [events]
    verbs: [create]
