{{- if .Values.installCRDs -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logstash-inputs.logstash-operator.qalo.de
spec:
  scope: Namespaced
  group: logstash-operator.qalo.de
  names:
    kind: logstash-input
    plural: logstash-inputs
    singular: logstash-input
    shortNames:
      - lsi
      - lsis
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                data:
                  type: string
                service:
                  type: object
                  properties:
                    type:
                      type: string
                    port:
                      type: integer
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  {{- end}}