{{- if .Values.installCRDs -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logstash-pipelines.logstash-operator.qalo.de
spec:
  scope: Namespaced
  group: logstash-operator.qalo.de
  names:
    kind: logstash-pipeline
    plural: logstash-pipelines
    singular: logstash-pipeline
    shortNames:
      - lsp
      - lsps
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                selector:
                  type: string

            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  {{- end}}