apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "logstash-operator.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "default" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logstash-operator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: logstash-operator-account