apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "logstash-operator.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "default" }}
rules:

  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  - apiGroups: [batch, extensions]
    resources: [jobs]
    verbs: [create]
