apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstash-operator.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
  {{- include "logstash-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "logstash-operator.selectorLabels" . | nindent 4 }}
