apiVersion: logstash-operator.qalo.de/v1
kind: logstash-input
metadata:
  name: input1
  labels:
    nanocosmos.de/pipeline: pipeline1
spec:
  port: 5044
  data: |
    beats {
      port => 5044
    }
---
apiVersion: logstash-operator.qalo.de/v1
kind: logstash-input
metadata:
  name: input2
  labels:
    nanocosmos.de/pipeline: pipeline1
spec:
  port: 5045
  data: |
    beats {
      port => 5045
    }
---
apiVersion: logstash-operator.qalo.de/v1
kind: logstash-input
metadata:
  name: input3
  labels:
    nanocosmos.de/pipeline: pipeline2
spec:
  port: 5044
  data: |
    beats {
      port => 5044
    }