apiVersion: logstash-operator.qalo.de/v1
kind: logstash-filter
metadata:
  name: filter
spec:
  filter: |
    input {
      beats {
        port => 5044
      }
    }

    output {
      stdout {
        codec => rubydebug
      }
    }