apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-operator
  labels:
    app: logstash-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: logstash-operator
  template:
    metadata:
      labels:
        app: logstash-operator
    spec:
      serviceAccountName: logstash-operator-account
      containers:
      - name: logstash-operator
        image: 66runner/logstash-operator:latest
