apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logstash-filters.logstash-operator.qalo.de
spec:
  scope: Namespaced
  group: logstash-operator.qalo.de
  names:
    kind: logstash-filter
    plural: logstash-filters
    singular: logstash-filter
    shortNames:
      - lsf
      - lsfs
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                data:
                  type: string
                order: 
                  type: integer
                  default: 50
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
