apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logstash-patterns.logstash-operator.qalo.de
spec:
  scope: Namespaced
  group: logstash-operator.qalo.de
  names:
    kind: logstash-pattern
    plural: logstash-patterns
    singular: logstash-pattern
    shortNames:
      - lso
      - lsos
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                data:
                  type: string

            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
