apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logstash-deployments.logstash-operator.qalo.de
spec:
  scope: Namespaced
  group: logstash-operator.qalo.de
  names:
    kind: logstash-deployment
    plural: logstash-deployments
    singular: logstash-deployment
    shortNames:
      - lsd
      - lsds
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                pipelines:
                  type: array
                  items:
                    type: string
                    pattern: "^[a-z0-9]+(-[a-z0-9]+)*$"
                  default: 
                  - default
                config:
                  type: object
                  properties:
                    queue:
                      type: object
                      properties:
                        type:
                          type: string

            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true

