name: Release and publish helm artifact

on:
  push:
    tags:
      - '*'
      
jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      id: version
    - name: build package
      working-directory: deploy
      run: helm package --app-version ${{ steps.version.outputs.version }} logstash-operator
    - name: create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload helm artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./deploy/logstash-operator-${{ steps.version.outputs.version }}.tgz
        asset_name: logstash-operator-${{ steps.version.outputs.version }}.tgz
        asset_content_type: application/gzip
